#!/bin/bash

# Stop and remove all containers
docker ps -qa | xargs docker stop
docker ps -qa | xargs docker rm

# Remove all images
docker rmi -f $(docker images -q)

# Remove all volumes
docker volume prune -f -a